# Generated by Django 5.1.4 on 2024-12-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="nominations",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="user",
        ),
        migrations.CreateModel(
            name="CandidateNomination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("votes_count", models.PositiveIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_nominations",
                        to="awards.candidate",
                    ),
                ),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_nominations",
                        to="awards.nomination",
                    ),
                ),
            ],
            options={
                "unique_together": {("candidate", "nomination")},
            },
        ),
    ]
