# Generated by Django 5.1.4 on 2024-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0002_remove_candidate_nominations_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
