services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ops/api.Dockerfile
    volumes:
      - ../:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis

  bot:
    container_name: bot
    build:
      context: ../
      dockerfile: ops/Dockerfile
    depends_on:
      - api
      - db
      - redis
    ports:
      - "8080:8000"
    env_file:
      - .env
    restart: unless-stopped

  db:
    container_name: db
    restart: unless-stopped
    image: postgres:17.2
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.4.0
    ports:
      - '6380:6380'
    env_file:
      - .env
    volumes:
      - redis_data:/var/lib/redis
    command: ["redis-server", "--port", "6380"]

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: my_network